version: '3'

tasks:
  install:
    desc: Build and start the Docker containers
    cmds:
      - cmd: cp apps/web/.env.dist apps/web/.env
        ignore_error: true
      - task: bootstrap
      - task: ssl

  start:
    desc: Start the Docker containers

    cmds:
      - docker compose up -d
      - task: migrations
        vars:
          CLI_ARGS: --no-interaction

  stop:
    desc: Stop the Docker containers
    cmds:
      - docker compose down

  ssl:
    internal: true
    cmds:
      - mkcert -key-file certs/local-key.pem -cert-file certs/local-cert.pem *.app.localhost app.localhost
      - mkcert -install
    status:
      - test -f certs/local-cert.pem
      - test -f certs/local-key.pem

  bootstrap:
    cmds:
      - docker compose -f docker-compose.yml -f docker-compose.tools.yml build
      - docker compose pull
      - task: composer_install
      - task: yarn_install

  composer_install:
    cmds:
      - task: composer
        vars:
          CLI_ARGS: install --no-interaction --no-progress --prefer-dist
    sources:
      - ./apps/api/composer.json
      - ./apps/api/composer.lock
    generates:
      - ./apps/api/vendor/**/*

  yarn_install:
    cmds:
      - task: yarn
        vars:
          CLI_ARGS: install --frozen-lockfile
    sources:
      - ./apps/web/package.json
      - ./apps/web/yarn.lock
    generates:
      - ./apps/web/.yarn/install-state.gz
      - ./apps/web/node_modules/**/*

  composer:
    desc: Shortcut to run Composer CLI
    cmds:
      - docker compose run --rm php composer {{.CLI_ARGS}}

  console:
    desc: Shortcut to run Symfony console
    cmds:
      - docker compose run --rm php console {{.CLI_ARGS}}

  phpstan:
    desc: Shortcut to run PHPStan
    cmds:
      - docker compose -f docker-compose.tools.yml run --rm phpstan {{.CLI_ARGS}}

  deptrac:
    desc: Shortcut to run Deptrac
    cmds:
      - docker compose -f docker-compose.tools.yml run --rm deptrac {{.CLI_ARGS}}

  cs-fixer:
    desc: Shortcut to run PHP CS Fixer
    cmds:
      - docker compose -f docker-compose.tools.yml run --rm cs-fixer {{.CLI_ARGS}}

  rector:
    desc: Shortcut to run Rector
    cmds:
      - docker compose -f docker-compose.tools.yml run --rm rector {{.CLI_ARGS}}

  pest:
    desc: Shortcut to run Pest
    cmds:
      - docker compose run --rm php vendor/bin/pest {{.CLI_ARGS}}

  yarn:
    desc: Shortcut to run Yarn CLI
    cmds:
      - docker compose run --rm node yarn {{.CLI_ARGS}}

  eslint:
    desc: Shortcut to run Eslint CLI
    cmds:
      - docker compose run --rm node eslint {{.CLI_ARGS}}

  migrations:
    desc: Shortcut to run Doctrine migrations
    cmds:
      - task: console
        vars:
          CLI_ARGS: doctrine:database:create --if-not-exists {{.CLI_ARGS}}
      - task: console
        vars:
          CLI_ARGS: doctrine:migrations:migrate {{.CLI_ARGS}}
